name: "Web app setup"
description: "Set up NPM and dependencies"

runs:
  using: "composite"
  steps:
    - name: ci/setup-node
      uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
      id: setup_node
      with:
        node-version-file: ".nvmrc"
        cache: npm
        cache-dependency-path: 'webapp/package-lock.json'
    - name: ci/get-node-modules
      shell: bash
      working-directory: webapp
      run: |
        make node_modules
